#define READ_OK 1

#define MIN_MENU 0
#define MAX_MENU 9

#define MIN_HOME_SIZE 1
#define MAX_HOME_SIZE 999

#define MIN_APPART_SIZE 1
#define MAX_APPART_SIZE 999

#define MAX_ROOMS 15
#define MIN_ROOMS 1

#define MAX_SQUARE_PRICE 1000000
#define MIN_SQUARE_PRICE 1

#define MAX_AREA 1000
#define MIN_AREA 1

#define MAX_SIZE_LAST_CNT 15
#define MIN_SIZE_LAST_CNT 1

#define MAX_SIZE_PREV_CNT 20
#define MIN_SIZE_PREV_CNT 1

#define MAX_BUILD_TIME 2019
#define MIN_BUILD_TIME 1900

#define STR_MAX_SIZE 46

#define OK 0
#define INVALID_INPUT 1
#define INVALID_MENU_NUMBER 2
#define FILE_ERROR 3
#define INVALID_FILE_SIZE 4
#define INVALID_ROOMS_SIZE 5
#define INVALID_MAX_AREA_SIZE 6
#define INVALID_SQUARE_PRICE 7
#define INVALID_IS_PRIMARY 8
#define INVALID_HOME_SIZE 9
#define INVALID_APPART_SIZE 10
#define INVALID_IS_DECORATION 11
#define INVALID_LAST_COUNT 12
#define INVALID_BUILD_TIME 13
#define INVALID_IS_ANIMALS 14
#define INVALID_PREVIOUS_COUNT 15
#define TABLE_IS_FULL 16
#define NO_APPART 17
#define INVALID_SORT_TYPE 18
#define TABLE_IS_EMPTY 19
#define INVALID_TABLE_TYPE 20
#define INVALID_DIAPASONE 22
